M48
; DRILL file {KiCad 9.0.4} date 2025-10-16T22:23:17+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-16T22:23:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.092
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X185.094Y-132.5
T2
X185.094Y-111.5
T3
X85.0Y-60.0
X85.0Y-145.0
X205.0Y-60.0
X205.0Y-145.0
M30
